services:
  gott-calculator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gott-calculator
    expose:
      - "80"
    restart: unless-stopped
    networks:
      - cloudflare_default

networks:
  cloudflare_default:
    external: true